#!/bin/bash

backup=
cache=
metadata=
factory=
oem=
userdata=

mopts='noatime,nodiratime,discard,barrier,journal_checksum,data=journal,commit=5,errors=panic'

mount -t sysfs -o 'nodev,noexec,nosuid' sysfs /sys
for syspath in /sys/class/block/* ; do
    part="$(sed -ne 's/^PARTNAME=\(backup\|cache\|metadata\|factory\|oem\|userdata\)$/\1/p;T;q' "${syspath}/uevent")"
    if [ "$part" ] ; then
        devpath="/dev/$(basename "${syspath}")"
        eval "${part}=\"\${devpath}\""
    fi
done
umount /sys

#for part in backup cache metadata factory oem userdata ; do
#    eval "devpath=\"\${${part}}\""
#    echo "linuxrc: ${part}: devpath=${devpath}"
#done
    
if [ -e "${userdata}" ] &&
    (
        fsck.ext4 -p "${userdata}"
        [ $? -lt 4 ] && mount -t 'ext4' -o "rw,${mopts}" "${userdata}" /data
    ) || (
        fsck.ext4 -f -y "${userdata}"
        [ $? -lt 4 ] && mount -t 'ext4' -o "rw,${mopts}" "${userdata}" /data
    ) || (
        mkfs.ext4 -F "${userdata}"
        [ $? -eq 0 ] && mount -t 'ext4' -o "rw,${mopts}" "${userdata}" /data
    )
then
    rm -rf /data/overlay/linux-work
    mkdir -p /data/overlay/{linux,linux-work}
    mount --bind / /boot
    if mount -t 'overlay' -o 'lowerdir=/boot,upperdir=/data/overlay/linux,workdir=/data/overlay/linux-work' overlay /boot ; then
        cd /boot
        if pivot_root . boot ; then
            mount --move /boot/data /data
            mount --move /boot/dev /dev
            umount /boot/boot

            for part in backup cache metadata factory ; do
                eval "devpath=\"\${${part}}\""
                if [ -e "${devpath}" ] ; then
                    mkdir -p "/.android/${part}" &&
                    mount -t 'ext4' -o "ro,${mopts}" "${devpath}" "/.android/${part}"
                fi
            done

            if [ -e "${oem}" ] ; then
                mkdir -p '/oem' &&
                mount -t 'squashfs' -o 'defaults' "${oem}" '/oem'
            fi

            exec chroot . /sbin/init
        fi
        cd /
        umount /boot
    fi
    umount /boot
fi
#umount /data

#bash -i
exec /sbin/init
